### ISSUE TITLE
(Feature suggestion) add start value and animation length 

### ISSUE THREAD

**Issue by realisticedge9457** [InventiveRhythm/fluXis#101]
### Type

Other

### Version

..

### Description of the bug

Submission by -joako

-Add the “use start value” and the “animation length” to the scroll velocity trigger
so you don't have to add 30 triggers that slow down every one second.
it could be one that slows down the velocity in a certain period of time until it reaches X point.

-I mean to simplify this thing basically xd

### Screenshots/Video

![image-1](https://github.com/user-attachments/assets/58ed032f-65ee-4ff4-ad4b-64f5d27bd2f5)

**Comment by JoakoU** [comment]
🙏🥺
