### ISSUE TITLE
Why it

### ISSUE THREAD

**Issue by kitoraosu** [InventiveRhythm/fluXis#102]
### Type

Behavior

### Version

v2024.15.0 (latest on 12.11.2024)

### Description of the bug

https://github.com/user-attachments/assets/74b6d2f6-e815-4753-9a50-708d042141fe

### Please add game mechanic as:
-- When player have combo and minimum HP, (+Hard mod)
--- Player can't Fail,
-- When player hit miss, (lost combo)
--- Player Fail

### Or Fix please Hard mod
-- I hit 300s or 300 and my HP with Hard mod just go down

### Screenshots/Video

https://github.com/user-attachments/assets/74b6d2f6-e815-4753-9a50-708d042141fe

**Comment by flustix** [comment]
You are 20 versions behind the latest. (The most revent is 2024.34.0)

The hard mod behavior has been changed in 2024.22.0 so that it is now affected by health difficulty, making it so that the mapper has to properly set the HP value.

Also this is not a proper issue title.
