### ISSUE TITLE
Mouse visible

### ISSUE THREAD

**Issue by NightMelody** [InventiveRhythm/fluXis#104]
### Type

Crash/Error/Exception

### Version

2024.34

### Description of the bug

The OS mouse is visible inside fluXis...
Only that

**Comment by flustix** [comment]
Screenshot? Operating System?? Nothing???

**Comment by NightMelody** [comment]
Windows 11 and...
It's literally what I say, the mouse is visible in the game

Screenshot...
Uh...

Oh...
It's solved, LMAO
I just changed my screen resolution and bum! Now the mouse is hidden

**Comment by NightMelody** [comment]
Well, the bug appeared when I changed the fluXis resolution
