### ISSUE TITLE
BPM Lines are too thin (Charting)

### ISSUE THREAD

**Issue by kaneryu** [InventiveRhythm/fluXis#11]
BPM lines (or snap lines) are too thin, at least least on my 720p display.
![image](https://github.com/TeamFluXis/fluXis/assets/72762358/6d300dc0-5342-4733-bd4a-05c5ea4a9eac)
![image](https://github.com/TeamFluXis/fluXis/assets/72762358/2fde86f7-a717-4ee1-89b6-427fcdf93795)
As you can see, scrolling makes different lines pop in an out of view. Unpausing fixes it, as when the song is playing, all lines are visible.

**Comment by flustix** [comment]
Fixed with [4d21028](https://github.com/TeamFluXis/fluXis/commit/4d210283018b77a49790dcf9b2b85b170a5c7e62)
