### ISSUE TITLE
Hold notes are allowed to be placed outside of charting area, causing game crash

### ISSUE THREAD

**Issue by kaneryu** [InventiveRhythm/fluXis#12]
Title.
Steps:
Start a hold note inside the charting area, then drag your mouse outside.
When you test, the game will crash.

I kind of think this 'feature' is cool, the crash should just be removed. Imagine if during a song's beatdrop notes come at you outside of the area, that would be fun (but probably not rankable).

**Comment by flustix** [comment]
Fixed with [2424b7f](https://github.com/TeamFluXis/fluXis/commit/2424b7f306d59fee2bc55824f80d32f4360ce7b0)
