### ISSUE TITLE
Editor: add "exit without saving" option

### ISSUE THREAD

**Issue by AncuL001** [InventiveRhythm/fluXis#14]
sometimes i just wanna play around with the map in the editor without actually saving

![image](https://github.com/TeamFluXis/fluXis/assets/16044057/aa4f7642-1fe7-404f-8e26-4dc41ea051da)

**Comment by AncuL001** [comment]
add some labels dawg

**Comment by flustix** [comment]
Pressing "yes" would just exit.

But next update is gonna have better labels.

**Comment by AncuL001** [comment]
Oh lol
