### ISSUE TITLE
Editor allows note overlapping

### ISSUE THREAD

**Issue by ReXGReMoRY** [InventiveRhythm/fluXis#15]
You can place notes on the same timestamp and overlap them.

**Comment by Comprobar** [comment]
eg. "HitObjects":[{"Lane":4,"HoldTime":0.0,"Time":500.0},{"Lane":4,"HoldTime":0.0,"Time":500.0}]

**Comment by flustix** [comment]
Fixed with [44db834](https://github.com/TeamFluXis/fluXis/commit/44db8347ec7076560d29f80ba52c754cbc0689d9).
