### ISSUE TITLE
i failed on nofail, putting logs here to see if it helps

### ISSUE THREAD

**Issue by Tempyseemoo** [InventiveRhythm/fluXis#17]
[network.log](https://github.com/TeamFluXis/fluXis/files/12776722/network.log)
https://cdn.discordapp.com/attachments/994669361203785789/1157960055287721984/image.png?ex=651a81d7&is=65193057&hm=f487c063344de2aa165b2ee6872b74acc18ed57f63b9ed67ac538be517bce45f&

**Comment by Tempyseemoo** [comment]
sent the wrong fucking file 
[runtime.log](https://github.com/TeamFluXis/fluXis/files/12776725/runtime.log)

**Comment by flustix** [comment]
Known issue, already fixed in the next update.
