### ISSUE TITLE
Music sometimes doesn't start when entering gameplay

### ISSUE THREAD

**Issue by Cyriod** [InventiveRhythm/fluXis#18]
Sometimes, if you input too fast by quitting the map and starting it again (I feel like), the music doesn't play at all.

I did reproduce the bug few times on any diff of the map:  Creo - Exoplanet (Cut Ver.) by Ucitysm
and with a custom map of my own by quitting another map and quickly starting my map

**Comment by flustix** [comment]
Apparently this was caused by the volume fade during the loading screen. Fixed in [b76f795](https://github.com/TeamFluXis/fluXis/commit/b76f795f2d1706af7571ca60d1c0209d57785f01)
