### ISSUE TITLE
Exporting tries to save with invalid characters

### ISSUE THREAD

**Issue by ReXGReMoRY** [InventiveRhythm/fluXis#24]
For some reason i cant export a map from fluxis.
And the same map crashes my game when i try to upload it.
Logs:
[update.log](https://github.com/TeamFluXis/fluXis/files/12794412/update.log)
[input.log](https://github.com/TeamFluXis/fluXis/files/12794414/input.log)
[network.log](https://github.com/TeamFluXis/fluXis/files/12794415/network.log)
[performance.log](https://github.com/TeamFluXis/fluXis/files/12794416/performance.log)
[runtime.log](https://github.com/TeamFluXis/fluXis/files/12794417/runtime.log)

**Comment by flustix** [comment]
That might be because the song contains quotes, and you can't use quotes as file names in windows.
Seems to be an easy fix though.

**Comment by flustix** [comment]
Fixed with [d1fb49c](https://github.com/TeamFluXis/fluXis/commit/d1fb49c09c390da072e91682fb77029fa4d87026)
