### ISSUE TITLE
(Feature Request) Timing Groups

### ISSUE THREAD

**Issue by kaneryu** [InventiveRhythm/fluXis#29]
Hm...

With this change, each note would belong to a timing group, sharing the BPM, time sig, notespeed. By default all notes would be in the same timing group (bassically no change), however you could add more timing groups to allow notes to move at different speeds to eachother.

**Comment by flustix** [comment]
I don't see how a group of notes would need a different BPM.

We had something similar planned for Scroll Velocities where you can pick what lanes it applies to.

**Comment by kaneryu** [comment]
Yes, you are right with BPM, no need for that.
SV being per timing group is more usefull, because it can do both (for example, you can put all notes in lane one in timing group one and you can do it for specific notes)

**Comment by flustix** [comment]
Per-Lane SV has been added.
