### ISSUE TITLE
LN's visually shorten as map rate increases

### ISSUE THREAD

**Issue by PuzzlyPop** [InventiveRhythm/fluXis#30]
Basically the title. As you increase the map rate, LN's visually shorten. They seem to play the same in terms of hold length, so I have no idea what's going on.

**Comment by flustix** [comment]
I.. am not quite sure what is meant by this

Images would be pretty helpful here

**Comment by PuzzlyPop** [comment]
Length of LN's on 1.0 (first pic) vs length on 2.0
https://imgur.com/a/OqTJ8ak

**Comment by PuzzlyPop** [comment]
idk if this is an issue due to scroll speed changing somehow or what, since the scroll speed decrease is very obvious past 2.0x. Can't really tell if my scrollspeed is going down before 2.0 but it feels like it might be

**Comment by flustix** [comment]
This seems perfectly fine to me. They kinda are supposed to be shorter since they are faster no?
