### ISSUE TITLE
"Keep Holding"

### ISSUE THREAD

**Issue by ReimBuch5851551** [InventiveRhythm/fluXis#31]
I was playing some map and the game said "Keep Holding". I'm an experienced osu!mania player and I can hold long notes for long enough, so this was weird to me. It was not just the long notes, it also appeared to be the normal notes and I missed for no reason. 

More info:
-Played with CV.-
-It was a osu!mania map
-Scroll speed 4

**Comment by flustix** [comment]
That "Keep holding..." is for the quick restart/exit keybinds

**Comment by flustix** [comment]
And the "missing for no reason" is because the keybinds are the same.
The keybind system prefers UI before gameplay
