### ISSUE TITLE
Settings Dialog doesn't close when clicking Import Files

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#32]
https://github.com/TeamFluXis/fluXis/assets/75596775/37b6bdb4-0556-464f-9f13-11774d6619d0

**Comment by flustix** [comment]
Fixed with [01d0b39](https://github.com/TeamFluXis/fluXis/commit/01d0b3960ba757e1978063cded6b0fa49900b07a)
