### ISSUE TITLE
Now playing info on main menu uses last song before switching

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#33]
https://github.com/TeamFluXis/fluXis/assets/75596775/7ce3ed0c-0926-4508-a494-6ed4701aac71

**Comment by flustix** [comment]
Fixed with [a40bccd](https://github.com/TeamFluXis/fluXis/commit/a40bccd4e015c52cffd16a0facfdfbb88d647402)
