### ISSUE TITLE
Player can still complete a level despite failure

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#34]
https://github.com/TeamFluXis/fluXis/assets/75596775/a51060bb-71dc-475d-88ef-169fd7379288

Also has the side effect of turning on "Daycore mode" when going back to song select.

**Comment by flustix** [comment]
Fixed with [d828c26](https://github.com/TeamFluXis/fluXis/commit/d828c264da80bb4eaaec90fe39abc53e0dac1b37)
