### ISSUE TITLE
Score tooltip still shows score info when a score is deleted

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#35]
https://github.com/TeamFluXis/fluXis/assets/75596775/c18e13b4-f4e5-4390-ba83-55709baef0e9

**Comment by flustix** [comment]
Fixed with [0e05894](https://github.com/TeamFluXis/fluXis/commit/0e05894bf78ebd92e16b6f80905c7d288e427c7d)
