### ISSUE TITLE
Failure animation should only play once regardless of missing notes during the animation

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#37]
https://github.com/TeamFluXis/fluXis/assets/75596775/ca833e31-3343-44ff-bd11-4fcfee286838

I could not find better wording than this so here's a video as always.

**Comment by flustix** [comment]
Fixed with [d828c26](https://github.com/TeamFluXis/fluXis/commit/d828c264da80bb4eaaec90fe39abc53e0dac1b37)
