### ISSUE TITLE
Prevent miss sounds from playing when rewinding

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#38]
https://github.com/TeamFluXis/fluXis/assets/75596775/8abaa64f-4916-40ed-84b2-15fe5a548ef2

Volume Warning!

**Comment by flustix** [comment]
Fixed with [f65defc](https://github.com/TeamFluXis/fluXis/commit/f65defcc8b02973d3d2a4523f8bf180761c6395e)
