### ISSUE TITLE
fail.wav should not leak through screens nor retries

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#39]
https://github.com/TeamFluXis/fluXis/assets/75596775/3661998c-f4f9-4eba-86f2-7d6237c502e0

On a similar vein as https://github.com/ppy/osu/issues/22173

**Comment by flustix** [comment]
Fixed with [1952055](https://github.com/TeamFluXis/fluXis/commit/1952055b8accf85728a46bbc9b657f380f70bdad)
