### ISSUE TITLE
Score screen from logged-in players' scores are unviewable when logged out

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#40]
https://github.com/TeamFluXis/fluXis/assets/75596775/ee93961a-1ab9-43c2-a91a-5d2fb765c003

**Comment by flustix** [comment]
Fixed with [f0dcb3f](https://github.com/TeamFluXis/fluXis/commit/f0dcb3f074ea6c3fcf809282025fc1b88b7221f4).
