### ISSUE TITLE
Hovering over context menu dropdowns should not recenter song select list to currently selected song

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#42]
https://github.com/TeamFluXis/fluXis/assets/75596775/9168c883-c574-4cb5-9891-83731d0c5938

**Comment by flustix** [comment]
Fixed with [74c51f7](https://github.com/TeamFluXis/fluXis/commit/74c51f7451400f14b75fc3af96c84254ad2e5809)
