### ISSUE TITLE
Extremely long metadata titles can overflow out of the results screen

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#43]
![image](https://github.com/TeamFluXis/fluXis/assets/75596775/66d052ef-c3e2-41e9-a7aa-51291d2f4577)

**Comment by flustix** [comment]
Fixed with [600adfd](https://github.com/TeamFluXis/fluXis/commit/600adfdf500b2707971c8f03c16caea4d8bec4f9)
