### ISSUE TITLE
Dialog prompts should focus input to themselves

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#46]
https://github.com/TeamFluXis/fluXis/assets/75596775/2218a5e0-d5e2-4b1f-b2d1-851b8a0229e0

It should've deleted the map when I pressed Enter!
(Maybe related with https://github.com/TeamFluXis/fluXis/issues/19 ?)

**Comment by flustix** [comment]
It has nothing with to do with focus. The `FullInputBlockingContainer` doesn't handle global keybindings
