### ISSUE TITLE
Song playback speed doesn't return to normal when exiting the map after a failure

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#47]
https://github.com/TeamFluXis/fluXis/assets/75596775/e15f9fe9-753b-45a9-9507-ddb6d410492f

Instantly fixes itself by selecting another map.

**Comment by flustix** [comment]
This one is kinda wierd.. It started happening after I updated the framework. So it could either be a framework bug or something in our code missing.
