### ISSUE TITLE
Updater shouldn't force-close the game without user consent

### ISSUE THREAD

**Issue by nagi-desuuu** [InventiveRhythm/fluXis#52]
### Is this a new issue?

- [x] Yes, I checked the other issues.

### fluXis version

```Markdown
- fluXis version: 2023.22.0
```

### Device

```Markdown
- Device: Windows 10
```

### Description of the bug

After downloading an update, after a brief notification, the program closes without any regard whether if a player is on gameplay or not.

### Expected behavior

The game should have a persistent notification notifying users that an update is available, and shouldn't quit the program right away.

### Steps to reproduce

Have an available update, and then go into gameplay. It's that simple, really.

### Screenshots/Video

(Not applicable)

**Comment by flustix** [comment]
Closing this as it won't matter soon anyway.
