### ISSUE TITLE
The provided body is missing the 'hash' property.

### ISSUE THREAD

**Issue by kitoraosu** [InventiveRhythm/fluXis#56]
### Is this a new issue?

- [X] Yes, I checked the other issues.

### fluXis version

fluXis v2024.4.0
![image](https://github.com/TeamFluXis/fluXis/assets/30956599/59ffbaef-1603-407c-b220-ce59a51a61f3)
don't send scores, bug with POST (or GET) body request

### Device

Windows 10

### Description of the bug

don't send scores, bug with POST (or GET) body request
"The provided body is missing the 'hash' property."
Maybe don't send coverted maps?

### Expected behavior

...

### Steps to reproduce

...

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/30956599/d82bcb7e-4d29-4495-b5b7-87d218f47983)

**Comment by nagi-desuuu** [comment]
https://discord.com/channels/994666749570076764/994684038633750589/1199781150386823229

**Comment by flustix** [comment]
Fixed with [e6e1309](https://github.com/TeamFluXis/fluXis/commit/e6e13096b8f4df2c5dcb850d96065b7be0579839).
