### ISSUE TITLE
Music Player not change track name

### ISSUE THREAD

**Issue by kitoraosu** [InventiveRhythm/fluXis#57]
### Is this a new issue?

- [X] Yes, I checked the other issues.

### fluXis version

fluXis v2024.4.0

### Device

Windows 10

### Description of the bug

Music Player not change track name

### Expected behavior

Music Player not change track name

### Steps to reproduce

listen music, click music player

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/30956599/314dbab8-d1b5-41e4-bfd4-f124add06582)

**Comment by flustix** [comment]
This should have been fixed already but I did a mistake and the last update didn't contain any of the new changes. Relaunching the game should fix it.
