### ISSUE TITLE
Really slow beatmap cover/background image loading in Online Map Browser

### ISSUE THREAD

**Issue by LukynkaCZE** [InventiveRhythm/fluXis#59]
Not sure where to report this since there is no public repository for the API/Server 

The loading of covers and backgrounds is really slow and inefficient due to their size _(up to 3840x2160 in some instances)_. It both takes long and takes unnecessary space in memory. I really recommend storing way lower resolution version for preview purposes in the online map browser. osu! for examples stores preview covers in resolution of 300x300, you can't really see the difference in resolution since the preview cover is pretty small in the actual game anyways

![a](https://github.com/TeamFluXis/fluXis/assets/48604271/7300317f-f1d8-4b3b-b117-838833718005)

**Comment by LukynkaCZE** [comment]
Here is example of difference between current vs small resolution (4:3 images resized to 300px,300px and 16:9 to 480px,270px)

https://github.com/TeamFluXis/fluXis/assets/48604271/22ddf50e-1b03-41ac-ae97-9df558cc8157

About 80% faster

**Comment by flustix** [comment]
This should load a lot faster now. 👍
