### ISSUE TITLE
Installer timeout windows 11

### ISSUE THREAD

**Issue by RaoraRare** [InventiveRhythm/fluXis#6]
<img width="960" alt="Screenshot 2023-08-15 171723" src="https://github.com/TeamFluXis/fluXis/assets/120297366/12253af6-eed1-48b5-9347-be6190af37d8">
<img width="960" alt="Screenshot 2023-08-15 171750" src="https://github.com/TeamFluXis/fluXis/assets/120297366/2805fc29-0980-4e17-ae51-74c74f28f5dd">
when trying to install FluXis on my PC I get errors though the issue may be on my side idk.

**Comment by flustix** [comment]
It's an issue with your internet being too slow, I'll make a fix for it soon™

**Comment by RaoraRare** [comment]
Ok
