### ISSUE TITLE
Passing a song and appearing as first place in the leaderboard for global.

### ISSUE THREAD

**Issue by turtless24** [InventiveRhythm/fluXis#61]
### Is this a new issue?

- [X] Yes, I checked the other issues.

### fluXis version

v.2024.9.1

### Device

Windows 11 Lenovo Laptop.

### Description of the bug

When you click no fail for a map and pass it even though you have failed the map it will still show up that you have completed the map and have become the first place person on a global leaderboard. 

### Expected behavior

You shouldn't have appeared on a global leaderboard nor appear on any other leaderboard except a local one.

### Steps to reproduce

Turn on the No fail mod and then select a map, fail the map and then look at the leaderboard and see you have placed first place on a global leaderboard.

### Screenshots/Video

![image_2024-03-23_123526314](https://github.com/TeamFluXis/fluXis/assets/157861064/7f00f8dc-ec5a-4138-b3b0-1429bf6d4ee3)
![Uploading Screenshot 2024-03-23 123337.png…]()

**Comment by flustix** [comment]
Intended. NoFail scores are supposed to appear even if you failed.

**Comment by nagi-desuuu** [comment]
I mean, it's already in the name...
