### ISSUE TITLE
Discord RPC bug

### ISSUE THREAD

**Issue by kitoraosu** [InventiveRhythm/fluXis#62]
### Type

Crash/Error/Exception

### Version

v2024.12.0 (Version From Installer)

### Description of the bug

Discord RPC bug:
random bug (random `In the Menus` and `Playing` status):
> `Selecting a Song` -> `Loading...` -> `In the Menus`
`Selecting a Song` -> `Loading...` -> `Playing`
`In the Menus` (In Map) -> `Pause` -> `In the Menus` (In Map)
`In the Menus` (In Map) -> `Pause` -> `Playing`
`Playing` -> `Pause` -> `Playing`

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/30956599/7cfc0f04-679a-46a6-9abd-df4711e7b92a)

**Comment by flustix** [comment]
Can't really seem to reproduce this one. Will investigate more later.

If you manage to come across the issue again, please send me the network log.
