### ISSUE TITLE
Discord username checker broken

### ISSUE THREAD

**Issue by kitoraosu** [InventiveRhythm/fluXis#65]
### Type

Crash/Error/Exception

### Version

v2024.15.0

### Description of the bug

![image](https://github.com/TeamFluXis/fluXis/assets/30956599/cd34bb49-6581-4e24-8666-e38410f599b8)

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/30956599/c0faf57c-2270-44d6-ad09-1b77eee77473)

**Comment by flustix** [comment]
Server-side issue. Should be fixed now.
