### ISSUE TITLE
"Not Responding" when importing a large number of maps via drag n' drop

### ISSUE THREAD

**Issue by tractorbeam0** [InventiveRhythm/fluXis#66]
### Type

Behavior

### Version

I can't check lol. should be 2024.15

### Description of the bug

I have some (280) maps from osu that I imported into fluxis, and while the game continued to run normally, with the notification animations, and the music playing in the background and everything, windows claimed it wasn't responding. Windows is great.

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/37884919/cf714da2-35a3-4274-8320-2fe8ec2fcc3c)

**Comment by tractorbeam0** [comment]
it just finished, I am indeed running 2024.15.0

**Comment by flustix** [comment]
Known issue. Happens because the import is running on the Input thread.

**Comment by flustix** [comment]
Should be fixed with `a170db2`. Might need some improvements later but its good for now.
