### ISSUE TITLE
Exit animation doesn't account for ultrawide monitors

### ISSUE THREAD

**Issue by tractorbeam0** [InventiveRhythm/fluXis#67]
### Type

Other

### Version

2024.16.0

### Description of the bug

L+Ratio+Git Gud+Bozo

### Screenshots/Video

![image](https://github.com/TeamFluXis/fluXis/assets/37884919/87b7f7bf-6a86-47dd-9881-0a5d305dd833)

**Comment by nagi-desuuu** [comment]
Next time, don't roast the developers by just mentioning that in your report statement...

**Comment by tractorbeam0** [comment]
'Twas a joke, sir. I am a semi-active member in their discord and this is the sort of humor I see all around the place, this is an obscure but easy to fix issue so I thought I'd apply it here for the funny. I apologize if it was not taken that way.
