### ISSUE TITLE
offset wizard doesn't work

### ISSUE THREAD

**Issue by Tempyseemoo** [InventiveRhythm/fluXis#7]
changing offset doesn't offset the offset song

**Comment by flustix** [comment]
It... does?

I just tested it and it does change the offset.

**Comment by Tempyseemoo** [comment]
i did this on v2023.13.1 is it outdated

**Comment by flustix** [comment]
https://github.com/TeamFluXis/fluXis/assets/65369281/798bbfc6-5279-4e61-9cc3-7aecfbb29c09

**Comment by Tempyseemoo** [comment]
i have no fucking clue what happened but i restarted my game 3 times and it works
