### ISSUE TITLE
Scrolling Snap Desync

### ISSUE THREAD

**Issue by svKona** [InventiveRhythm/fluXis#73]
### Type

Behavior

### Version

v2024.16.0

### Description of the bug

Scrolling through the playfield with scroll wheel does not match up with the beats created by the timing point.

Note: The desync issue grows larger the further you are from the timing point. Said timing point in this specific map is 220 BPM.

### Screenshots/Video

https://github.com/TeamFluXis/fluXis/assets/70233392/b4df1b43-c12c-4d41-aae7-dc090ff1b2e6

**Comment by flustix** [comment]
This is already fixed and will be pushed next update.

**Comment by svKona** [comment]
oh ,
