### ISSUE TITLE
fluXis throwing a BadMatch error when trying to launch it after setting the renderer to vulkan

### ISSUE THREAD

**Issue by iolo53435343** [InventiveRhythm/fluXis#74]
### Type

Crash/Error/Exception

### Version

2024.16.0-linux

### Description of the bug

After downloading the linux version, i tried to set the renderer to vulkan, which prompted a restart to the game. After the restart, i was unable to launch the game again. After trying to launch it through terminal (to see what it outputs), i got this error:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Serial number of failed request:  397
  Current serial number in output stream:  453

I also tried cloning and building it with the given commands, which gave me the same error.

**Comment by flustix** [comment]
Vulkan renderer is very very very experimental. This is a framework issue and can't really be fixed by me. 

You can change the renderer back to "Automatic" by editing the file at `~/.local/share/fluXis/framework.ini` (I think thats the location?) and changing `Renderer =` to `Renderer = Automatic`

**Comment by iolo53435343** [comment]
Changing the renderer in the file path given got my game to launch properly now, big thanks for that.
I noticed the experimental stated in the settings, i was just curious with the performance differences in the renderer.

**Comment by nagi-desuuu** [comment]
Does the built-in renderer setting not work?

**Comment by iolo53435343** [comment]
built-in rendering works, i was just curious about vulkan and its performance. It stopped launching properly AFTER i changed the renderer to vulkan.
