### ISSUE TITLE
Design Tab doesn't preview effects correctly

### ISSUE THREAD

**Issue by 7xbi** [InventiveRhythm/fluXis#76]
### Type

Behavior

### Version

v2024.18.1

### Description of the bug

Refer to the video attatched below
Editor makes it seem like the effect is exactly placed in the middle of the screen, making it look seemless while the actual gameplay is way different.

### Screenshots/Video

https://github.com/TeamFluXis/fluXis/assets/48262626/22b21b8a-804a-4eb9-83c6-9fd576b9d398

**Comment by flustix** [comment]
Fixed with last update.
