### ISSUE TITLE
Upscroll issue

### ISSUE THREAD

**Issue by nabd-om** [InventiveRhythm/fluXis#78]
### Type

Other

### Version

v2024.19.1

### Description of the bug

so i'm an upscroll player and when i changed the scroll from down to up some things seems to disappear like judgements, judgement bar, accuracy and rating (A, S, SS,etc) i don't know if someone knew about this but yeah, this happens.

### Screenshots/Video

same map with the same skin

https://github.com/TeamFluXis/fluXis/assets/175151959/1a04603f-06d4-43e0-9265-9fa9b4893ce4

https://github.com/TeamFluXis/fluXis/assets/175151959/0dc1c6ff-a012-4387-b26f-4baf11fddcad

**Comment by flustix** [comment]
Has been resolved a few updates ago.
