### ISSUE TITLE
Keypresses failing to register.

### ISSUE THREAD

**Issue by OjisanHoshino** [InventiveRhythm/fluXis#82]
### Type

Other

### Version

v2024.20.0

### Description of the bug

Basically, when i tried to hit this, the game wouldn't register all the keypresses. This isn't a keyboard related issue as i tried the same thing in osu afterwards and hit it perfectly without any issues. I'm not sure if it only happens on quads but i have experienced the same issue on a dense chordjack chart.

### Screenshots/Video

Pattern/section of chart i was mentioning in the description. I would attach a video of the problem but it doesn't happen everytime.
![image](https://github.com/user-attachments/assets/74d4b840-36eb-4e2f-a4fc-55eb09f21ca0)

**Comment by flustix** [comment]
What are your keybinds?

**Comment by OjisanHoshino** [comment]
zx;'
