### ISSUE TITLE
Editor preview/Editor gameplay Issue

### ISSUE THREAD

**Issue by ReXGReMoRY** [InventiveRhythm/fluXis#83]
### Type

Behavior

### Version

v2024.22.0

### Description of the bug

When i place some move triggers in the editor the gameplay moves perfectly the way it should (althought sometimes it does not) but when i play the map itself outside editor the gameplay is not the same, in my case, i placed a move trigger to x: 0 y= -1100 (to bring the gameplay outside the eyes of the player) then on the next timing point i placed another move trigger like this x: 0 y: 0, (in order to move the gameplay back in place but slowly, coming from above because of the previously move trigger that was Y: -1100), in the editor it shows, but outside the editor playing it by itself it does not apply. This is maybe a "unique" bug, that does not apply always

PD: I managed to fix it by editing the move trigger to y: -1000 instead of -1100, for some reason it just does not work.

**Comment by flustix** [comment]
I fixed this a while ago when adding shader preview.
