### ISSUE TITLE
Audio Quality Degrades After Failing Out Multiple Times

### ISSUE THREAD

**Issue by windows-phone67** [InventiveRhythm/fluXis#84]
### Type

Behavior

### Version

v2024.24.0

### Description of the bug

When you fail out, a filter gets applied to the audio but doesn't get removed when you quit or retry. After a while its pretty hard to hear the music while playing the game.

### Screenshots/Video

https://drive.google.com/file/d/1202pMcmyIGJWIOoBtyQ-qJe0-IHJkpRS/view?usp=sharing

**Comment by flustix** [comment]
Seems to be an issue with the health overlay.
I'll investigate more later

**Comment by flustix** [comment]
Okay found the issue. Should be fixed next update.
