### ISSUE TITLE
Maps without a Title break letter navigation

### ISSUE THREAD

**Issue by GamingWithJanko** [InventiveRhythm/fluXis#85]
### Type

Crash/Error/Exception

### Version

Beta (v2024.24.0)

### Description of the bug

Open game, immediately open mods (F1) and press W repeatedly.

Boom, crashed.

### Screenshots/Video

Video was too big... So...

https://youtu.be/mw3F2Mi6r3k

**Comment by GamingWithJanko** [comment]
Apparently this causes it too:
https://youtu.be/ASd6phVGA9Y

Map used:
https://quavergame.com/mapset/map/147576

Same procedure.

**Comment by flustix** [comment]
Completely unrelated to mods, this happens because the currently selected song does not have a title.

**Comment by GamingWithJanko** [comment]
That's how it looks in the file:
![image](https://github.com/user-attachments/assets/7e016c2a-4239-4395-9a3c-7debf7b392e5)

And that's in Quaver:
![image](https://github.com/user-attachments/assets/edfc47e6-f61d-4eb4-8b90-5167d9d19441)

The "No title" is intentional, as seen here:
https://www.youtube.com/watch?v=_q-J3QYT98g
That's the video from the artist themselves.

It's some kind of whitespace character, according to "Emik" (Mapper of the map).
