### ISSUE TITLE
Changing offset during pause can cause misses

### ISSUE THREAD

**Issue by Kori3** [InventiveRhythm/fluXis#89]
### Type

Behavior

### Version

2024.28.0

### Description of the bug

self explanatory ig

It can even cause the player to lose if enough notes go past the hit window.

### Screenshots/Video

https://github.com/user-attachments/assets/64a98948-0d0e-476e-a543-e3350ba7b9d3

**Comment by flustix** [comment]
I don't know what a potential fix for this could even be. Because just updating the offset when un-pausing makes you die regardless.

**Comment by Kori3** [comment]
checked osu lazer and yes it happens there too lol. idk its just that something feels wrong when you miss or fail while the game is paused. at least in osu lazer the offset isn't applied until the game resumes

**Comment by flustix** [comment]
Closing as this isn't that big of an issue.
