### ISSUE TITLE
Lane switch event decimal separator

### ISSUE THREAD

**Issue by jouneee** [InventiveRhythm/fluXis#9]
Make lane switch events save like flash events.

Because due to locale differences time stamps save with a comma, which results in an error and softlocks the game.

![изображение](https://github.com/TeamFluXis/fluXis/assets/111516089/2acec6ed-731a-4c01-9a06-6b566b675fab)
![изображение](https://cdn.discordapp.com/attachments/1084169545020874893/1157360326342344724/image.png?ex=6518534c&is=651701cc&hm=7f36e7d1e09332c2188883753243e7476dadde27de52e16d70b1d409ca043ba7&)

**Comment by flustix** [comment]
Stupid oversight from me. Should be fixed in [1493ac8](https://github.com/TeamFluXis/fluXis/commit/1493ac897df09d28edde80d14a6a4d900cc820bf).
