### ISSUE TITLE
Account Problems

### ISSUE THREAD

**Issue by ReimBuch5851551** [InventiveRhythm/fluXis#90]
### Type

Behavior

### Version

v2024.28.0

### Description of the bug

Before I start crying about the problem, I'm not a professional GitHub Issue filer, I'm just some dude with a problem I can't solve myself. So about the problem:

I can't change my password with the e-mail adress that was linked to the account. I'm not sure anymore if I had an account already, because if I cannot login in any way possible, that if I create a new account, I don't get banned because I'm "allegedly" multiaccounting. I know, the messing up the information part is on me, but that the e-mail adress I linked doesn't work for password change is bad.

The screenshot I linked below obviously doesn't show my e-mail adress, but this is the result afterwards.

Kind regards,
ReimBuch5851551

### Screenshots/Video

![Bild_2024-09-20_195115714](https://github.com/user-attachments/assets/0957182a-8b3e-4751-9474-8ae3d1c9d4ad)

**Comment by flustix** [comment]
I might have forgotten to update that when i changed it on the backend. (Although i'm pretty sure i changed it)

I will check later!

**Comment by flustix** [comment]
The website seems up-to-date. I rebuilt it so maybe try again?

**Comment by ReimBuch5851551** [comment]
It could be possible that I just didn't create an account, but I'm pretty sure I did. Because I don't want to get banned due to multiaccounting, could you check, if there is any account under the name "ReimBuch"? If yes, then there really is an issue with the login. If not, then there is probably no account my e-mail is referring to. Nevertheless, thank you for your help.

Kind regards,
ReimBuch5851551

**Comment by flustix** [comment]
Your account does exist. 

After more checking I actually found the issue so this should be fixed now.

**Comment by ReimBuch5851551** [comment]
I know the issue now, at least the core of it. It has to do with the browser. I just tried it out in Edge and it worked, but in Opera (GX) it showed this weird error message. I will put it as resolved for now, but if you want to find out the issue with Opera, now you know it exists.

Kind regards,
ReimBuch5851551

**Comment by flustix** [comment]
The issue applied to every browser, it was in the javascript code.
