### ISSUE TITLE
I can't download repetitions

### ISSUE THREAD

**Issue by elmatero** [InventiveRhythm/fluXis#91]
### Type

Crash/Error/Exception

### Version

v2024.29.0

### Description of the bug

**For a few days now I have wanted to download replays but I always have the same error**

### Screenshots/Video

https://github.com/user-attachments/assets/e01291af-60e3-4ba2-9389-ca6769a9c6f9

**Comment by flustix** [comment]
There is a button in Settings > Maintenance to clean up leftover scores

**Comment by flustix** [comment]
Wait no I just noticed thats not the issue

Might be because the replay file doesn't exist server-side? I'm gonna have to check whats up with that

**Comment by flustix** [comment]
Issue ended up being a server-side bug. Every replay was saved as ID 0, effectively wiping each other.
